package dst

func (v *ArrayType) isNode()      {}
func (v *AssignStmt) isNode()     {}
func (v *BadDecl) isNode()        {}
func (v *BadExpr) isNode()        {}
func (v *BadStmt) isNode()        {}
func (v *BasicLit) isNode()       {}
func (v *BinaryExpr) isNode()     {}
func (v *BlockStmt) isNode()      {}
func (v *BranchStmt) isNode()     {}
func (v *CallExpr) isNode()       {}
func (v *CaseClause) isNode()     {}
func (v *ChanType) isNode()       {}
func (v *CommClause) isNode()     {}
func (v *CompositeLit) isNode()   {}
func (v *DeclStmt) isNode()       {}
func (v *DeferStmt) isNode()      {}
func (v *Ellipsis) isNode()       {}
func (v *EmptyStmt) isNode()      {}
func (v *ExprStmt) isNode()       {}
func (v *Field) isNode()          {}
func (v *FieldList) isNode()      {}
func (v *File) isNode()           {}
func (v *ForStmt) isNode()        {}
func (v *FuncDecl) isNode()       {}
func (v *FuncLit) isNode()        {}
func (v *FuncType) isNode()       {}
func (v *GenDecl) isNode()        {}
func (v *GoStmt) isNode()         {}
func (v *Ident) isNode()          {}
func (v *IfStmt) isNode()         {}
func (v *ImportSpec) isNode()     {}
func (v *IncDecStmt) isNode()     {}
func (v *IndexExpr) isNode()      {}
func (v *InterfaceType) isNode()  {}
func (v *KeyValueExpr) isNode()   {}
func (v *LabeledStmt) isNode()    {}
func (v *MapType) isNode()        {}
func (v *ParenExpr) isNode()      {}
func (v *RangeStmt) isNode()      {}
func (v *ReturnStmt) isNode()     {}
func (v *SelectStmt) isNode()     {}
func (v *SelectorExpr) isNode()   {}
func (v *SendStmt) isNode()       {}
func (v *SliceExpr) isNode()      {}
func (v *StarExpr) isNode()       {}
func (v *StructType) isNode()     {}
func (v *SwitchStmt) isNode()     {}
func (v *TypeAssertExpr) isNode() {}
func (v *TypeSpec) isNode()       {}
func (v *TypeSwitchStmt) isNode() {}
func (v *UnaryExpr) isNode()      {}
func (v *ValueSpec) isNode()      {}
func (v *Package) isNode()        {}
func (v *DecorationStmt) isNode() {}
func (v *DecorationDecl) isNode() {}
